### ISSUE TITLE
Topic format conversion in jig

### ISSUE THREAD

**Issue by johanneskiesel** [osirrc/jig#13]
Conversion of topic formats should be done in the jig, not by the search script inside the container.

This makes it easier to write the search script. I also think it is easier to maintain (i.e., adding new formats) the jig than to update the search script of an image.

**Comment by lintool** [comment]
My $0.02: I think most academic search engines already support the various topic formats... so I don't think this is necessary...

**Comment by r-clancy** [comment]
Closing this as the topic formats are fairly standardized - introducing some intermediate representation via `jig` would be cumbersome for image authors to write adapters for.
