### ISSUE TITLE
Why are we doing this?

### ISSUE THREAD

**Issue by lintool** [osirrc/jig#54]
From @guidozuc and @hscells - on Slack, worth capturing:

> 1. is the idea to create test standard methods implemented in these tools to provide common baselines (read BM25, LM, DFR, SDM, etc), or push the envelope and create something more (read e.g. LTR)?
> 2. do we want systems to be comparable, or retrieval models to be comparable? What we mean is: pre-processing could provide large performance differences between the methods, even if the indexing and retrieval are identical. Do we want to control for having a standard pre-processing? Or everyone is free?
> 3. We could not work out hot to setup indexing and retrieval parameters from jig. For example, say you want to run BM25: you would like to be able to set the parameter values. Or do you assume that the hook we implement sets the parameters? That would mean the parameter for a tool need to be the same for each collection
> I think all these questions sum up to clarifying the fundamental understanding of what we are doing, and why

My response:

> 1. yes
> 2. I think at this stage we just want runs to be replicable. "I don't believe your results!" "Here's my docker image - you can easily confirm the results."
> 3. I believe the latest version of the jig has the ability to pass &rest - params that are relayed directly to the underlying image

@guidozuc 

> 1. A or B?
> 2. uhm... though since we now the qrels, just having a docker may mean the results are replicable w the docker, but the method does not do what we claim it does -- ie can just fit the qrels for example. That is, without source code we cannot be fully certain
> 3. great!

My response:

> 1. A... and then B.
> 2. Well, the image is transparent right? It is easy to inspect to see if it's cheating... that is, if it's cloning a git repo, compiling, and actually executing code, then we know... Also, with the image we can easily run on blind topics, not possible to fake.

**Comment by arjenpdevries** [comment]
I think it is a clear step forward, that can help us getting to all those other little and larger issues that will remain to be addressed. But a step forward it will be!!

**Comment by lintool** [comment]
Having "done it", closing...
