### ISSUE TITLE
NYT Manifest 

### ISSUE THREAD

**Issue by amallia** [osirrc/jig#64]
Attached is the md5sum for all the files in NYT (my copy).

[NYT.md5](https://gist.github.com/amallia/5b3ba7d8a556125f8c5b69ffae9c650b)

**Comment by r-clancy** [comment]
[validation.txt](https://github.com/osirrc2019/jig/files/3129599/validation.txt)
Looks good to me... here's the md5 comparison of our copy. Everything except a few missing HTML/README files in the tools dir looks good.

**Comment by r-clancy** [comment]
Closing this as we're document it in https://github.com/osirrc/jig/pull/94
