### ISSUE TITLE
Agree on collection name/id of web collections

### ISSUE THREAD

**Issue by lintool** [osirrc/jig#76]
The official names are GOV2, ClueWeb09b, ClueWeb12-B13 - this is correct casing. But for ids we sometimes downcase everything? i.e., `robust04`?

Doesn't really matter - we just need to agree on something...

README doesn't have a catalog of the collections...? Should we create such a table, add existing and above?

**Comment by r-clancy** [comment]
I'm fine with either the full name or lowercased, short name, as long as everything is consistent. `core17`, `core18`, `cw09b`, `cw12b13`, `robust04` to follow what's there currently and keep compatibility with any images that assume lowercase?

I can add a table once we come to a decision.

**Comment by lintool** [comment]
your proposals above are fine... and `gov2`.

**Comment by r-clancy** [comment]
Fixed in https://github.com/osirrc/jig/pull/77

**Comment by JMMackenzie** [comment]
Is it possible to just use `cw12b` since it's safe to assume people know what that is? Not a huge deal but it does make the clueweb stuff a bit more consistent IMO.

**Comment by lintool** [comment]
fine with me too if someone has an opinion... cc @r-clancy

**Comment by r-clancy** [comment]
Fine with me - I'll make the change.

**Comment by JMMackenzie** [comment]
Thanks!
