### ISSUE TITLE
Versioning Images

### ISSUE THREAD

**Issue by r-clancy** [osirrc/jig#79]
What route should we take for versioning the images? We can either hardcode commit ids or version numbers and tag the Docker image, specify a version in the `init` hook via the `--version` param to checkout a certain commit or download an artifact (which we may want to remove if we used the first route), or something else.

Thoughts? 

@lintool

**Comment by lintool** [comment]
What about: tag the docker repo with standard GitHub tools, make sure they align with the version published on DockerHub?

**Comment by r-clancy** [comment]
Seems reasonable to me - tag a commit on GitHub and push to DockerHub with the same tag (while `master` branch still stays in sync with `latest` Docker tag). I'll remove the `--version` param from the `init` hook as this way seems nicer...
