### ISSUE TITLE
Clueweb queries only

### ISSUE THREAD

**Issue by amallia** [osirrc/jig#96]
the topic for cb09 and cw12 are in xml format. TREC also distributes the query only, i.e. https://trec.nist.gov/data/web/10/wt2010-topics.queries-only.
Can we have these too in the jig, so we do not have to have an xml parser?

**Comment by r-clancy** [comment]
Can you provide a list of files you want included (or submit a PR) and I can add them?

**Comment by amallia** [comment]
https://trec.nist.gov/data/web/2014/web2014.topics.txt
https://trec.nist.gov/data/web/12/queries.151-200.txt
https://trec.nist.gov/data/web/2013/web2013.topics.txt
https://trec.nist.gov/data/web/11/queries.101-150.txt
https://trec.nist.gov/data/web/10/wt2010-topics.queries-only

**Comment by lintool** [comment]
Probably want to rename for consistency...
